### ISSUE TITLE
LOC_OT crashes

### ISSUE THREAD

**Issue by pzemlyan** [mjuvela/LOC#5]
The LOC_Cartesian_test failes with the exception:
USING  program.Update                                                                                  
Traceback (most recent call last):                                                                     
  File "/home/pzemlyan/pycorefit/corefit/loc/LOC_OT.py", line 346, in <module>                         
    kernel_sim.set_scalar_arg_dtypes([                                                                 
  File "/usr/lib/python3/dist-packages/pyopencl/__init__.py", line 860, in kernel_set_arg_types        
    generate_enqueue_and_set_args(                                                                     
  File "/usr/lib/python3/dist-packages/pyopencl/invoker.py", line 325, in generate_enqueue_and_set_args
    result = invoker_cache[cache_key]                                                                  
  File "/usr/lib/python3/dist-packages/pytools/persistent_dict.py", line 548, in __getitem__           
    return self.fetch(key, _stacklevel=1)                                                              
  File "/usr/lib/python3/dist-packages/pytools/persistent_dict.py", line 642, in fetch                 
    hexdigest_key = self.key_builder(key)                                                              
  File "/usr/lib/python3/dist-packages/pytools/persistent_dict.py", line 259, in __call__              
    self.rec(key_hash, key)                                                                            
  File "/usr/lib/python3/dist-packages/pytools/persistent_dict.py", line 239, in rec                   
    method(inner_key_hash, key)                                                                        
  File "/usr/lib/python3/dist-packages/pytools/persistent_dict.py", line 292, in update_for_tuple      
    self.rec(key_hash, obj_i)                                                                          
  File "/usr/lib/python3/dist-packages/pytools/persistent_dict.py", line 239, in rec                   
    method(inner_key_hash, key)                                                                        
  File "/usr/lib/python3/dist-packages/pytools/persistent_dict.py", line 292, in update_for_tuple      
    self.rec(key_hash, obj_i)                                                                          
  File "/usr/lib/python3/dist-packages/pytools/persistent_dict.py", line 243, in rec                   
    raise TypeError("unsupported type for persistent hash keying: %s"                                  
TypeError: unsupported type for persistent hash keying: <class 'numpy.dtypes.VoidDType'>               

Python 3.10.12
pyopencl version: (2021, 2, 13)
opencl version: 3.0~2022.01.04

The error seems to be solved by redefining REAL3 and cl.cltypes.float3 as None in LOC_OT.py file. My expirience with pyopencl is very limited so I am not sure is the solution fine or not.

The patch is attached.
[complex_types.patch.txt](https://github.com/mjuvela/LOC/files/14792936/complex_types.patch.txt)

**Comment by mjuvela** [comment]
The error with cl.cltypes.float3 may be related to some changes in pyopencl. I tested the LOC_Cartesian_test on CPU (using POCL) and on GPU (both NVidia and AMD GPUs, with the latest drivers), and the test ran without errors. I am using pyopencl version 1:2023.1-3 (with Python 3.11.8, on Linux). If possible, please update pyopencl to a more recent (and preferably the latest) version and see if that solves the problem. It may be that replacing the type definition with None can sidestep the problem... but I do not quite know why, and it might not be the right solution in long term.

**Comment by pzemlyan** [comment]
There is no such problem appears on modern linux distribution. Thanks for the great project.
